### ISSUE TITLE
Error: yo generator-jhipster-paypal

### ISSUE THREAD

**Issue by adrianosb** [contribution-jhipster-uga/generator-jhipster-paypal#2]
$ yo generator-jhipster-paypal
Installed generators don't need the "generator-" prefix.
In the future, run yo jhipster-paypal instead!

events.js:174
      throw er; // Unhandled 'error' event
      ^

TypeError: this.getJhipsterAppConfig is not a function
    at module.exports.readConfig (/home/adriano/.npm-global/lib/node_modules/generator-jhipster-paypal/generators/app/index.js:20:47)
    at Object.<anonymous> (/home/adriano/.npm-global/lib/node_modules/generator-jhipster-paypal/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:424:27)
    at /home/adriano/.npm-global/lib/node_modules/generator-jhipster-paypal/node_modules/run-async/index.js:25:25
    at new Promise (<anonymous>)
    at /home/adriano/.npm-global/lib/node_modules/generator-jhipster-paypal/node_modules/run-async/index.js:24:19
    at self.env.runLoop.add.completed (/home/adriano/.npm-global/lib/node_modules/generator-jhipster-paypal/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:425:13)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
Emitted 'error' event at:
    at Immediate.setImmediate (/home/adriano/.npm-global/lib/node_modules/generator-jhipster-paypal/node_modules/generator-jhipster/node_modules/yeoman-generator/lib/index.js:433:22)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by adrianosb** [comment]
jhipster v 6.1.2
npm v 6.9.0

**Comment by adrianosb** [comment]
in index.js, replace :
`this.jhipsterAppConfig = this.getJhipsterAppConfig();`

By
`this.jhipsterAppConfig = this.getAllJhipsterConfig();`
